# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0019_auto_20150426_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communal',
            name='ZKX_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u0416\u041a\u0425 - \u043e\u043f\u043b\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='course',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430 \u043d\u0430 \u0434\u0430\u0442\u0443 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='el_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u042d\u043b\u0435\u043a\u0442\u0440\u043e\u044d\u043d\u0435\u0440\u0433\u0438\u044f - \u043e\u043f\u043b\u0430\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='gas_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u0413\u0430\u0437 - \u043e\u043f\u043b\u0430\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='hot_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u0422\u0435\u043f\u043b\u043e\u044d\u043d\u0435\u0440\u0433\u0438\u044f - \u043e\u043f\u043b\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='penalty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u041f\u0435\u043d\u044f'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='phone_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d - \u043e\u043f\u043b\u0430\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='phone_tar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d - \u043d\u0430\u0447\u0438\u0441\u043b\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='prev_per',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u041f\u0440\u0435\u0434\u044b\u0434\u0443\u0449\u0438\u0439 \u043f\u0435\u0440\u0438\u043e\u0434'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='repair_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u041a\u0430\u043f\u0440\u0435\u043c\u043e\u043d\u0442 - \u043e\u043f\u043b\u0430\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='tv_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u0413\u043e\u0440\u0430\u0442\u043e\u0440\u0433 - \u043e\u043f\u043b\u0430\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='tv_tar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u0413\u043e\u0440\u0430\u0442\u043e\u0440\u0433 - \u043d\u0430\u0447\u0438\u0441\u043b\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='water_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u0412\u043e\u0434\u0430 - \u043e\u043f\u043b\u0430\u0447\u0435\u043d\u043e'),
        ),
        migrations.AlterField(
            model_name='communal',
            name='zhirovka',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='\u0421\u0443\u043c\u043c\u0430 \u0438\u0437 \u0436\u0438\u0440\u043e\u0432\u043a\u0438'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='resource',
            field=models.IntegerField(choices=[(1, '\u044d\u043b\u0435\u043a\u0442\u0440\u043e'), (2, '\u0433\u0430\u0437'), (3, '\u0432\u043e\u0434\u0430'), (4, '\u0432\u043e\u0434\u043e\u0441\u043d\u0430\u0431\u0436\u0435\u043d\u0438\u0435'), (5, '\u0432\u043e\u0434\u043e\u043e\u0442\u0432\u0435\u0434\u0435\u043d\u0438\u0435')], verbose_name='\u0422\u0438\u043f \u0440\u0435\u0441\u0443\u0440\u0441\u0430'),
        ),
    ]
