# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apart', '0020_auto_20160827_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communal',
            name='course',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='\u041a\u0443\u0440\u0441 \u0434\u043e\u043b\u043b\u0430\u0440\u0430 \u043d\u0430 \u0434\u0430\u0442\u0443 \u043e\u043f\u043b\u0430\u0442\u044b'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='text',
            field=models.TextField(blank=True, default=b'', verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439'),
        ),
    ]
