# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20150419_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj',
            name='course',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='proj',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='proj',
            name='usd',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
