# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0003_auto_20160710_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proj',
            name='course',
            field=models.DecimalField(decimal_places=4, max_digits=15),
        ),
    ]
