# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0013_auto_20150427_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='\u0426\u0435\u043d\u0430'),
        ),
    ]
