# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-10 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_remove_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='summ',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
