from django.utils.translation import gettext_lazy as _

TAGS = {
    'BIRT': _('Birth'),
    'DEAT': _('Death'),
    'MARR': _('Marriage'),
    'MARL': _('Marriage License'),
    'MARS': _('Marriage Settlement'),
    'EVEN': _('Event'),
    'ADOP': _('Adoption'),
    'CHRA': _('Adult Christening'),
    'ANUL': _('Annulment'),
    'BAPM': _('Baptism'),
    'BAPL': _('Baptism LDS'),
    'BARM': _('Bar Mitzvah'),
    'BASM': _('Bas Mitzvah'),
    'BLES': _('Blessing'),
    'BURI': _('Burial'),
    'CAST': _('Caste'),
    'CAUS': _('Cause'),
    'CENS': _('Census'),
    'CHR':  _('Christening'),
    'CONF': _('Confirmation'),
    'CONL': _('Confirmation LDS'),
    'CREM': _('Cremation'),
    'DSCR': _('Physical Description'),
    'DIV':  _('Divorce'),
    'DIVF': _('Divorce Filed'),
    'EDUC': _('Education'),
    'MAIL': _('Email'),
    'EMIG': _('Emigration'),
    'ENDL': _('Endowment'),
    'ENGA': _('Engagement'),
    'FCOM': _('First Communion'),
    'GRAD': _('Graduation'),
    'IMMI': _('Immigration'),
    'INIL': _('Initiatory'),
    'NATI': _('Nationality'),
    'NATU': _('Naturalization'),
    'OCCU': _('Occupation'),
    'ORDN': _('Ordination'),
    'PHON': _('Phone'),
    'PROB': _('Probate'),
    'PROP': _('Property'),
    'RELI': _('Religion'),
    'RESI': _('Residence'),
    'RETI': _('Retirement'),
    'SLGC': _('Sealing Child'),
    'SLGS': _('Sealing Spouse'),
    'SSN':  _('Social Security Number'),
    'TITL': _('Title'),
    'WWW':  _('Web'),
    'WILL': _('Will'),
    'IDNO': _('Identification Number'),
    'NCHI': _('Children Count'),
    'NMR':  _('Marriage Count'),
    'FACT': _('Fact'),
    'RIN':  _('Record ID Number'),
    '_UID':_( '* _UID'),
    '_UPD':_( '* _UPD'),
    'PRIM':_( '* _PRIM'),
    'TOUT':_( '* _PRIM_CUTOUT'),
    'TION':_( '* _POSITION'),
    '_RIN':_( '* _PHOTO_RIN'),
    'SIZE':_( '* _FILESIZE'),
    'TOUT':_( '* _CUTOUT'),
    'FAM':  _('Family'),
    'FAMS': _('Family Spouse'),
    'FAMC': _('Family Child'),
    'NAME': _('Name'),
    'GIVN': _('Given Name'),
    'SURN': _('Surname'),
    'SEX':  _('Sex'),
    'DATE': _('Date'),
    'PLAC': _('Place'),
    'NOTE': _('Note'),
    'OBJE': _('Object'),
    'FORM': _('Format'),
    'FILE': _('File'),
    'SOUR': _('Source'),
    'PAGE': _('Page'),
    'ROLE': _('Role'),
    'DATA': _('Data'),
    'TEXT': _('Text'),
    'ABBR': _('Abbreviation'),
    'ADDR': _('Address'),
    'ADR1': _('Address 1'),
    'ADR2': _('Address 2'),
    'AFN':  _('Ancestral File Number'),
    'AGE':  _('Age'),
    'AGNC': _('Agency'),
    'ALIA': _('Alias'),
    'ANCE': _('Ancestors'),
    'ANCI': _('Ancestor Interest'),
    'ASSO': _('Associates'),
    'AUTH': _('Author'),
    'BLOB': _('Binary Object'),
    'CALN': _('Call Number'),
    'CHAN': _('Change'),
    'CHAR': _('Character'),
    'CHIL': _('Child'),
    'CITY': _('City'),
    'CONC': _('Concatenation'),
    'CONT': _('Continued'),
    'COPR': _('Copyright'),
    'CORP': _('Corporation'),
    'CTRY': _('Country'),
    'DESC': _('Descendants'),
    'DESI': _('Descendant Interest'),
    'DEST': _('Destination'),
    'FAMF': _('Family File'),
    'FAX':  _('Fax'),
    'FONE': _('Phonetic'),
    'GEDC': _('GEDCOM'),
    'HEAD': _('Header'),
    'HUSB': _('Husband'),
    'INDI': _('Individual'),
    'LANG': _('Language'),
    'LATI': _('Latitude'),
    'LEGA': _('Legatee'),
    'LONG': _('Longitude'),
    'MAP':  _('Map'),
    'MARB': _('Marriage Bann'),
    'MARC': _('Marriage Contract'),
    'MEDI': _('Media'),
    'NICK': _('Nickname'),
    'NPFX': _('Name Prefix'),
    'NSFX': _('Name Suffix'),
    'ORDI': _('Ordinance'),
    'PEDI': _('Pedigree'),
    'POST': _('Postal Code'),
    'PUBL': _('Publication'),
    'QUAY': _('Quality Of Data'),
    'REFN': _('Reference'),
    'RELA': _('Relationship'),
    'REPO': _('Repository'),
    'RESN': _('Restriction'),
    'RFN':  _('Record File Number'),
    'ROMN': _('Romanized'),
    'SPFX': _('Surnme Prefix'),
    'STAE': _('State'),
    'STAT': _('Status'),
    'SUBM': _('Submitter'),
    'SUBN': _('Submission'),
    'TEMP': _('Temple'),
    'TIME': _('Time'),
    'TRLR': _('Trailer'),
    'TYPE': _('Type'),
    'VERS': _('Version'),
    'WIFE': _('Wife'),
}